### ISSUE TITLE
Is this cool project alive?

### ISSUE THREAD

**Issue by ierehon1905** [prettier/plugin-swift#12]
Hello, I was glad to find a swift prettier package because I use VScode to edit my swift scripts 
but it seems that this plugin only works with old versions of swift

will there be any updates on it?

**Comment by vknabel** [comment]
Hi @ierehon1905,

Sadly this project didn't receive any commits since 4 years.
For swift there are two actively used formatters:

- [SwiftFormat by nicklockwood](https://github.com/nicklockwood/SwiftFormat) with [my VS Code extension](https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swiftformat)
- [swift-format by apple](https://github.com/apple/swift-format) with [my VS Code extension](https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-apple-swift-format)

**Full disclosure:** both VS Code extensions are maintained by me.
